workflows:
  local:
    node-project:
      dependencies:
        - '@liquid-labs/catalyst-resource-babel-and-rollup'
        - '@liquid-labs/catalyst-resource-eslint'
        - '@liquid-labs/catalyst-resource-jest'
      artifacts:
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 0
          path: Makefile
          purpose: >-
            Sets up standard target vars (like 'BUILD_TARGETS') and runs scripts
            from 'make'.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 10
          path: make/10-locations.mk
          purpose: Defines the most basic locations, like the source directory.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 10
          path: make/10-resources.mk
          purpose: Locates tool executables and configuration files.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 15
          path: make/15-data-finder.mk
          purpose: >-
            Sets up vars listing test data files which will need to be copied
            under the test staging dir.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 20
          path: make/20-js-src-finder.mk
          purpose: >-
            Sets up vars listing JS files which will need to be tested and
            built.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 50
          path: make/50-worker-manager-js.mk
          purpose: Builds the 'dist/worker-manager.js' artifact.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 55
          path: make/55-lint.mk
          purpose: Provides lint functionality with eslint.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 55
          path: make/55-test.mk
          purpose: Provides test functionality with jest.
        - builder: '@liquid-labs/catalyst-builder-node'
          version: 1.0.0-alpha.0
          priority: 95
          path: make/95-final-targets.mk
          purpose: >-
            Sets up the final basic targets (like 'build') based on the target
            vars (like 'BUILD_TARGETS').
      config:
        noDevInstall: true
        noDoc: true
  github:
    node-unit-test:
      artifacts:
        - builder: '@liquid-labs/catalyst-builder-github-workflows-node-unit-test'
          version: 1.0.0-alpha.0
          path: .github/workflows/unit-tests-node.yaml
          purpose: Runs node unit test CI/CD using a GitHub Workflow.
          config: {}
badges:
  coverage:
    dependencies: []
    artifacts:
      - builder: '@liquid-labs/catalyst-builder-badge-coverage'
        version: 1.0.0-alpha.0
        priority: 0
        content: >-
          [![coverage:
          89%](./.readme-assets/coverage.svg)](https://github.com/liquid-labs/worker-manager/pulls?q=is%3Apr+is%3Aclosed)
        path: >-
          /Users/zane/.liq/playground/liquid-labs/worker-manager/.readme-assets/coverage.svg
        purpose: Test coverage badge for README.md.
  github-workflow:
    dependencies: []
    artifacts:
      - builder: '@liquid-labs/catalyst-builder-badge-github-workflows'
        version: 1.0.0-alpha.0
        priority: '1'
        content: >-
          [![Unit
          tests](https://github.com/liquid-labs/worker-manager/actions/workflows/unit-tests-node.yaml/badge.svg)](https://github.com/liquid-labs/worker-manager/actions/workflows/unit-tests-node.yaml)
        purpose: Display status of 'Unit tests' GitHub Workflow.
        config: {}
