# This file was generated by @liquid-labs/catalyst-builder-node. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-builder-node for further details

#####
# build dist/worker-manager.js
#####

CATALYST_WORKER_MANAGER_JS:=$(DIST)/worker-manager.js
CATALYST_WORKER_MANAGER_JS_ENTRY=$(SRC)/index.mjs
BUILD_TARGETS+=$(CATALYST_WORKER_MANAGER_JS)

$(CATALYST_WORKER_MANAGER_JS): package.json $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(CATALYST_WORKER_MANAGER_JS_ENTRY) \
	  JS_OUT=$@ \
	  $(CATALYST_ROLLUP) --config $(CATALYST_ROLLUP_CONFIG)

#####
# end dist/worker-manager.js
#####
